// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Task struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Parameters           string   `protobuf:"bytes,2,opt,name=parameters,proto3" json:"parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Task) GetParameters() string {
	if m != nil {
		return m.Parameters
	}
	return ""
}

type Message struct {
	Messageid            string          `protobuf:"bytes,1,opt,name=messageid,proto3" json:"messageid,omitempty"`
	Userid               int64           `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Statefuldata         string          `protobuf:"bytes,3,opt,name=statefuldata,proto3" json:"statefuldata,omitempty"`
	Tasks                map[int32]*Task `protobuf:"bytes,4,rep,name=tasks,proto3" json:"tasks,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMessageid() string {
	if m != nil {
		return m.Messageid
	}
	return ""
}

func (m *Message) GetUserid() int64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *Message) GetStatefuldata() string {
	if m != nil {
		return m.Statefuldata
	}
	return ""
}

func (m *Message) GetTasks() map[int32]*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func init() {
	proto.RegisterType((*Task)(nil), "pb.Task")
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterMapType((map[int32]*Task)(nil), "pb.Message.TasksEntry")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_f80abaa17e25ccc8) }

var fileDescriptor_f80abaa17e25ccc8 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0x49, 0xbb, 0xce, 0xee, 0xce, 0x07, 0xb9, 0xe8, 0x28, 0x22, 0x63, 0xf4, 0x69, 0x0f,
	0x92, 0x87, 0x29, 0x38, 0xc4, 0xa7, 0x82, 0x8f, 0x82, 0x04, 0xff, 0xc0, 0x8d, 0x8d, 0x52, 0xba,
	0xda, 0x90, 0x9b, 0x0a, 0xfb, 0xa1, 0xfe, 0x1f, 0x69, 0x5a, 0xa9, 0x7b, 0xbb, 0xe7, 0x4b, 0xce,
	0xc9, 0xc9, 0x85, 0xd4, 0x6a, 0x69, 0x5d, 0xeb, 0x5b, 0x8c, 0xac, 0xce, 0x9f, 0x60, 0xf6, 0x46,
	0x5c, 0xe3, 0x25, 0x24, 0xbe, 0xb5, 0xd5, 0x7b, 0x26, 0x36, 0x62, 0xbb, 0x50, 0x83, 0xc0, 0x35,
	0x80, 0x25, 0x47, 0x8d, 0xf1, 0xc6, 0x71, 0x16, 0x85, 0xa3, 0x7f, 0x24, 0xff, 0x11, 0x70, 0xf6,
	0x62, 0x98, 0xe9, 0xd3, 0xe0, 0x0d, 0x2c, 0x9a, 0x61, 0xac, 0xca, 0x31, 0x65, 0x02, 0xb8, 0x82,
	0x79, 0xc7, 0xc6, 0x55, 0x65, 0x48, 0x89, 0xd5, 0xa8, 0x30, 0x87, 0x73, 0xf6, 0xe4, 0xcd, 0x47,
	0x77, 0x28, 0xc9, 0x53, 0x16, 0x07, 0xe3, 0x09, 0xc3, 0x5b, 0x48, 0x3c, 0x71, 0xcd, 0xd9, 0x6c,
	0x13, 0x6f, 0x97, 0xbb, 0x95, 0xb4, 0x5a, 0x8e, 0xaf, 0xca, 0xbe, 0x3c, 0x3f, 0x7f, 0x79, 0x77,
	0x54, 0xc3, 0xa5, 0xeb, 0x02, 0x60, 0x82, 0x78, 0x01, 0x71, 0x6d, 0x8e, 0xa1, 0x4f, 0xa2, 0xfa,
	0x11, 0xd7, 0x90, 0x7c, 0xd3, 0xa1, 0x33, 0xa1, 0xc8, 0x72, 0x97, 0xf6, 0x69, 0xbd, 0x41, 0x0d,
	0xf8, 0x31, 0xda, 0x8b, 0xe2, 0x0a, 0xd2, 0xb2, 0xd9, 0x3f, 0xdc, 0x4b, 0xab, 0x8b, 0xbf, 0x0f,
	0xbe, 0x0a, 0x3d, 0x0f, 0x7b, 0xbb, 0xfb, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xe0, 0xb2, 0x85, 0x62,
	0x43, 0x01, 0x00, 0x00,
}
